- name: configure backend server
  hosts: backend
  become: yes
  task:
  - name: disable current nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install mysql and nodejs
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nodejs
    - mysql

  - name: install python libraries
    ansible.builtin.pip: 
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - pyMySQL

  - name: create expense user
    ansible.builtin.user:
      user: expense

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
      
  - name: download directory from url
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /temp/backend.zip 

  - name: unzip backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy backend service
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service

  - name: import mysql schema
    community.mysql.mysql_db:
      name: all
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.parijathapractice.onlin
      state: import
      target: /app/schema/backend.sql

  - name: deamon reload and restart the service
    ansible.builtin.systemd_service:
      enabled: yes
      state: restarted
      deamon_reload: true
      name: backend
      

