- name: configure nginx server
  hosts: frontend
  become: yes
  tasks: 
  - name: install nginx service
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: enabled and start the nginx service
    ansible.builtin.service:
      name: nginx 
      enabled: yes
      state: started

  - name: delete html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download the frontend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: unzip frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy expense config file
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart nginx service
    ansible.builtin.service:
      name: nginx
      state: restarted
      